### ISSUE TITLE
After updating Slack install script fails

### ISSUE THREAD

**Issue by c-boston** [marchica/slack-black-theme#8]
My Slack updated automatically and when I tried to add the theme back in I get this error 

![image](https://user-images.githubusercontent.com/28357347/61470136-84ad3d80-a94e-11e9-9fed-b46b9d1ec757.png)

**Comment by marchica** [comment]
Looks like Slack 4.0.0 has packed its code better into an asar file. Haven't figured out how to modify it with pure PowerShell yet. The goal is to avoid requiring users to install Node or other third party software.

Added better error handling in the meantime.

**Comment by c-boston** [comment]
Is there a workaround I can do to reinstall?

**Comment by marchica** [comment]
Ok rewrote the patcher in Node.js since PowerShell doesn't handle asar files natively.

You and @cromzinc want to give it a [whirl](https://github.com/marchica/slack-black-theme/releases/download/4.0.2-0/slack-patcher-win.exe)? 😁

**Comment by c-boston** [comment]
Worked after I closed and reopened Slack!
